baseURL:            "https://zhaohuxing.github.io/"
languageCode:       "zh-CN"
title:              "别捉急"
theme:              "minos"
paginate:           10

# Code highlights
PygmentsCodeFences: true
PygmentsStyle:      "friendly"

# Site.params
params:
  smartToc:         true
  author:           Zhaohu Xing

# Site.menus
menu:
  main:
  - name:         "分类"
    url:          "/categories/"
    weight:       1
  - name:         "标签"
    url:          "/tags/"
    weight:       2
  - name:         "关于"
    url:          "/about/"
    weight:       3

taxonomies:
  tag:              "tags"
  category:         "categories"
